_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  new_relic_rpm: -20
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_bundler: 0
  anchor_link: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  cacheflush: 0
  cacheflush_entity: 0
  ckeditor5: 0
  comment: 0
  components: 0
  config: 0
  config_pages: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  efq: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  help: 0
  helper: 0
  history: 0
  image: 0
  imageapi_optimize: 0
  includer: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  lazy: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media: 0
  media_library: 0
  media_library_edit: 0
  media_oembed_control: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  mysql: 0
  node: 0
  options: 0
  origin_extend: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  phpass: 0
  quick_node_clone: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  responsive_image: 0
  role_delegation: 0
  scheduler: 0
  schema_article: 0
  schema_metatag: 0
  schema_organization: 0
  schema_web_page: 0
  schema_web_site: 0
  search: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  sitemap: 0
  smart_date: 0
  smart_date_recur: 0
  smart_trim: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  view_unpublished: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_jqueryui_datepicker: 0
  webform_ui: 0
  webp: 0
  weight: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  origin: 0
profile: minimal
