_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  comment__admin:
    menu_name: admin
    parent: system.admin_content
    weight: 2
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:view__files':
    menu_name: admin
    parent: system.admin_content
    weight: 3
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    menu_name: admin
    parent: system.admin_content
    weight: 4
    expanded: false
    enabled: true
  paragraphs_library__paragraphs_library_item__collection:
    menu_name: admin
    parent: system.admin_content
    weight: 5
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__media_type__edit_form__audio':
    enabled: true
    menu_name: admin
    parent: entity.media_type.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media__field_ui_fieldsaudio':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__media__defaultaudio':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__media__default__audio':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__media__default__audio':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media_type__devel_load__audio':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 4
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media_type__delete_form__audio':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:media__add__audio':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    weight: 0
