_core:
  default_config_hash: Pq64GZUb-bJckfjkDVfY82wzyy-XmRDovFeC0rFIBBc
page_title: Sitemap
message:
  value: ''
  format: restricted_html
plugins:
  book:
    enabled: false
    weight: -50
  'vocabulary:article_category':
    enabled: false
    weight: -49
    settings:
      title: 'Article Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:status':
    enabled: false
    weight: -48
    settings:
      title: Status
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:lodging_category':
    enabled: false
    weight: -47
    settings:
      title: 'Lodging Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:lifts_trails_type':
    enabled: false
    weight: -46
    settings:
      title: 'Lifts & Trails Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:level_category':
    enabled: false
    weight: -45
    settings:
      title: 'Level Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:event_category':
    enabled: false
    weight: -44
    settings:
      title: 'Event Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:dining_category':
    enabled: false
    weight: -43
    settings:
      title: 'Dining Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:condition_category':
    enabled: false
    weight: -42
    settings:
      title: 'Condition Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:age_category':
    enabled: false
    weight: -41
    settings:
      title: 'Age Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  frontpage:
    enabled: false
    weight: -40
    settings:
      title: 'Front page'
      rss: /rss.xml
  'vocabulary:activity_category':
    enabled: false
    weight: -39
    settings:
      title: 'Activity Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'menu:tools':
    enabled: false
    weight: -38
    settings:
      title: Tools
      show_disabled: false
  'menu:social':
    enabled: true
    weight: -35
    settings:
      title: ''
      show_disabled: false
  'menu:main':
    enabled: true
    weight: -37
    settings:
      title: ''
      show_disabled: false
  'menu:footer':
    enabled: true
    weight: -36
    settings:
      title: ''
      show_disabled: false
  'menu:devel':
    enabled: false
    weight: -34
    settings:
      title: Development
      show_disabled: false
  'menu:admin':
    enabled: false
    weight: -33
    settings:
      title: Administration
      show_disabled: false
  'menu:account':
    enabled: false
    weight: -32
    settings:
      title: 'User account menu'
      show_disabled: false
  'vocabulary:tags':
    enabled: false
    weight: -31
    settings:
      title: Tags
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
include_css: true
